//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDBEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableContact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableContact()
        {
            this.TableAdresses = new HashSet<TableAdress>();
        }
    
        public short id { get; set; }
        public short id_manufacturer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableAdress> TableAdresses { get; set; }
        public virtual TableManufacturerInfo TableManufacturerInfo { get; set; }
    }
}
