//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDBEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableExGuitarColor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableExGuitarColor()
        {
            this.TableColorSetsGuitars = new HashSet<TableColorSetsGuitar>();
        }
    
        public string BodyColor { get; set; }
        public string ColorAccessories { get; set; }
        public int id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableColorSetsGuitar> TableColorSetsGuitars { get; set; }
    }
}
