//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDBEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableDescriptionGuitar
    {
        public int id { get; set; }
        public short NumberOfStrings { get; set; }
        public string MountNeck { get; set; }
        public string BodyStyle { get; set; }
        public string BodyMaterial { get; set; }
        public string BridgeType { get; set; }
        public string NeckMaterial { get; set; }
        public string LiningMaterial { get; set; }
        public short NumberFrets { get; set; }
        public string PickupScheme { get; set; }
        public string PickupSwitch { get; set; }
        public Nullable<short> id_PickupManufacturer { get; set; }
        public Nullable<short> NumberVolumeControls { get; set; }
        public Nullable<short> NumberToneControls { get; set; }
    
        public virtual TableGuitar TableGuitar { get; set; }
        public virtual TableManufacturerInfo TableManufacturerInfo { get; set; }
    }
}
