//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDBEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablePhoneNumber
    {
        public string Number { get; set; }
        public string TypePhone { get; set; }
        public int id_adress { get; set; }
    
        public virtual TableAdress TableAdress { get; set; }
    }
}
