//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDBEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableAdress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableAdress()
        {
            this.TablePhoneNumbers = new HashSet<TablePhoneNumber>();
        }
    
        public string Country { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string House { get; set; }
        public Nullable<short> id_contact { get; set; }
        public int id { get; set; }
    
        public virtual TableContact TableContact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TablePhoneNumber> TablePhoneNumbers { get; set; }
    }
}
