//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDBEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableGuitar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableGuitar()
        {
            this.TableColorSetsGuitars = new HashSet<TableColorSetsGuitar>();
        }
    
        public int id { get; set; }
        public string TypeOfGuitar { get; set; }
        public short id_manufacturer { get; set; }
        public string Model { get; set; }
        public string CreationYearModel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableColorSetsGuitar> TableColorSetsGuitars { get; set; }
        public virtual TableDescriptionGuitar TableDescriptionGuitar { get; set; }
        public virtual TableManufacturerInfo TableManufacturerInfo { get; set; }
    }
}
