//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDBEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableColorSetsGuitar
    {
        public int id_color_set { get; set; }
        public int id_guitar { get; set; }
        public int id { get; set; }
    
        public virtual TableExGuitarColor TableExGuitarColor { get; set; }
        public virtual TableGuitar TableGuitar { get; set; }
    }
}
